language: node_js
node_js:
  - '0.10'
before_install: 
  - npm install -g grunt-cli bower
install:
  - npm install
  - bower install
  - bundle install
before_script:
  - grunt build
script: 
  - grunt test
env:
  secure: "T/LUu1vqouo9cONBC6IS7ti1bz5+NrWwEH+5NQGyCjnbQrE2OHqCDSJUL55+ynPMtI1GBe3/2HItl9fZDN4pYXnT9z67l55G7dcKPWD78hzQ91FgIgCb5oNGmU2s/94MgcEAT6z6C+octnAh+uYo2n2M05m1VXQ8ul+Ho7M6huU="
