language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli bower
install:
- npm install
- bower install
- bundle install
before_script:
- grunt build
script:
- grunt test
env:
  global:
  - secure: Ye5fhoHrugI9F9EWY7V1PLvRay02TtIbH55FDQdpgjI7Pg03aEja6U5TqbW7U0InRNPI6Eeh3sZAToVdmv4a0tUdlR/OAzf6gPo8cN4IwcDI2YPuoaAeGLKdb1rLZ/MtfN+Hab56RHWRgqzYsT/Cq3jrEejjRVbKyfyWlP+4I7A=
  - secure: QUBusQJmKe0xV4IoNhbgwPII3w866QgTzFEoQUwrprCIyykobGyef5+NCDXSWRA2A3tWHg1gLVUQfHDt6SNO4vtOEITb7bzIY63vFcwZ1B8az/YRrgxZVKkOcfmLuosXq+1LQFGc7tzgrkqUb6N7SSSMmnoWgNZ3D1GFqZ2rXh4=
addons:
  sauce_connect: true
